export const ICONS = [
'anticon anticon-area-chart',
'anticon anticon-pie-chart',
'anticon anticon-bar-chart',
'anticon anticon-dot-chart',
'anticon anticon-line-chart',
'anticon anticon-bars',
'anticon anticon-cloud',
'anticon anticon-desktop',
'anticon anticon-file-text',
'anticon anticon-hdd',
'anticon anticon-appstore',
'anticon anticon-picture',
'anticon anticon-heart',
'anticon anticon-environment',
'anticon anticon-eye',
'anticon anticon-camera',
'anticon anticon-solution',
'anticon anticon-pay-circle',
'anticon anticon-pay-bulb',
'anticon anticon-pay-rocket',
'anticon anticon-pay-global',
'anticon anticon-pay-table',
'anticon anticon-pay-bank',
'anticon anticon-pay-trophy',
'anticon anticon-pay-dashboard',
'anticon anticon-pay-dashboard',
];
